### ISSUE TITLE
tests fail when run from published crate

### ISSUE THREAD

**Issue by dkg** [slint-ui/document-features#15]
The process of publishing a crate appears to naturally strip the comments in `Cargo.toml`.

Consequently, when i try to build and run the code in this crate from the published crate, i end up with errors in the self-test.

The published crate (v0.2.6) has this Cargo.toml:

```toml
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite `path` dependencies
# to registry (e.g., crates.io) dependencies.
#
# If you are reading this file be aware that the original Cargo.toml
# will likely look very different (and much more reasonable).
# See Cargo.toml.orig for the original contents.

[package]
edition = "2018"
name = "document-features"
version = "0.2.6"
authors = ["Slint Developers <info@slint-ui.com>"]
description = "Extract documentation for the feature flags from comments in Cargo.toml"
homepage = "https://slint-ui.com"
readme = "README.md"
keywords = [
    "documentation",
    "features",
    "rustdoc",
    "macro",
]
categories = ["development-tools"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/slint-ui/document-features"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies.litrs]
version = "0.2.3"
default-features = false

[features]
default = []
self-test = []
```

This of course results in:

```
error: Could not find documented features in Cargo.toml
 --> tests/self-doc.rs:3:5
  |
3 |     document_features::document_features!();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `document_features::document_features` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This is a concern for me because i'm trying to package the `document-features` crate in debian, and the debian rust team is currently packaging based on the published crates.
