### ISSUE TITLE
Features that are transitively enabled by default are not rendered as "(enabled by default)"

### ISSUE THREAD

**Issue by vi** [slint-ui/document-features#19]
With

```toml
[features]
default=["qqq"]

## Qqq
qqq=["www"]

## Www
www=[]
```

I expect

* qqq _(enabled by default)_ — Qqq
* www _(enabled by default)_ — Www

, but get

* qqq _(enabled by default)_ — Qqq
* www — Www

.
