### ISSUE TITLE
Indent paragraphed comments under the resp. bullet point for a feature

### ISSUE THREAD

**Issue by virtualritz** [slint-ui/document-features#5]
```toml
[features]
default = []
## the `spline_inverse()` code will check if the knot vector is
## monotonic in *debug* builds.
##
## ⚠️ This only works when using a *nightly* toolchain.
unstable = []
```

Expected MD output:

* `unstable` — the `spline_inverse()` code will check if the knot vector is monotonic in *debug* builds.

  ⚠️ This only works when using a *nightly* toolchain.
  
Actual MD output:

* `unstable` — the `spline_inverse()` code will check if the knot vector is monotonic in *debug* builds.

⚠️ This only works when using a *nightly* toolchain.
